### PR TITLE
Bump minimum Swift version to 5.7

### PR DESCRIPTION
**Pull request by rnro**
Motivation:

Now that Swift 5.9 is GM we should update the supported versions and remove 5.6

Modifications:

* Update `Package.swift`
* Remove `#if swift(>=5.7)` guards
* Delete the 5.6 docker compose file and make a 5.10 one
* Update docs

Result:

Remove support for Swift 5.6, add 5.10

### CODE REVIEW

**Review by glbrntt — APPROVED** [review]

**Review by dnadoba — APPROVED** [review]
LGTM

**Review by Lukasa — APPROVED** [review]

**Comment by Lukasa** [comment]
@swift-server-bot add to allowlist

**Comment by Lukasa** [comment]
@yim-lee can we remove the 5.6 builder?

**Comment by rnro** [comment]
@swift-server-bot test this please

**Comment by yim-lee** [comment]
CI updated. @swift-server-bot test this please

**Pull request merged**
