### PR TITLE
Remove a couple of unnecessary imports

### PR DESCRIPTION
**Pull request by karwa**
These 2 Foundation imports are not required. 🧹

### CODE REVIEW

**Comment by dnadoba** [comment]
@swift-server-bot test this please

**Comment by fabianfett** [comment]
@swift-server-bot test this please

**Review by fabianfett — APPROVED** [review]
Good catch! Thanks @karwa

**Comment by fabianfett** [comment]
@tomerd Apparently the trigger CI command doesn't work anymore... 😞

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
@fabianfett It does, just not for you on this repo. :grin:

**Comment by Lukasa** [comment]
Soundness is failing, but it isn't your fault, it's due to #489. We should be able to unblock this quickly.

**Comment by yim-lee** [comment]
> Apparently the trigger CI command doesn't work anymore...

@fabianfett I fixed it (I think). PLMK if it still doesn't work for you.

**Pull request merged**
