### PR TITLE
Increase decompression limit ratio of `HTTPClient.shared` 10 -> 25

### PR DESCRIPTION
**Pull request by MahdiBM**
This enables the decompressor to decompress files that have been 96% compressed, instead of the previous 90%, when using `HTTPClient.shared`.

See https://github.com/swift-server/async-http-client/issues/739.

I'm also fine with decreasing the ratio to 20, if 25 seems too high.

### CODE REVIEW

**Comment by MahdiBM** [comment]
@Lukasa since you were responding on the issue 🙂

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Review by Lukasa — APPROVED** [review]
Nice, LGTM.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Pull request merged**
