### PR TITLE
Drop support for Swift 5.2 and 5.3

### PR DESCRIPTION
**Pull request by fabianfett**
As outlined in a [Swift forums post in November ’21](https://forums.swift.org/t/swiftnio-swift-version-support/53232), SwiftNIO will only support the latest non-patch Swift release and the 2 immediately prior non-patch versions.

In this commit we drop support for Swift 5.2 and 5.3. We update CI for Swift 5.4 to run on bionic instead of focal to ensure that we still test bionic. Also we use the new SPM API break checker.

### CODE REVIEW

**Comment by fabianfett** [comment]
@yim-lee Could you please disable the CI for 5.2 and 5.3 and change the CI file for 5.4 from `docker/docker-compose.2004.54.yaml` to `docker/docker-compose.1804.54.yaml`.

**Review by Lukasa — APPROVED** [review]
LGTM modulo CI changes

**Comment by yim-lee** [comment]
CI and branch rules updated.

@swift-server-bot test this please

**Comment by fabianfett** [comment]
Nightly and 5.7 fail because of Sendable requirements.

**Pull request merged**
