### PR TITLE
fix doc generation setup

### PR DESCRIPTION
**Pull request by tomerd**
motivation: fix doc generation - sourcekitten requires Swift 5.2

changes: expose the doc generation task on the 5.3 docker-compose file so we can trigger it there

### CODE REVIEW

**Comment by tomerd** [comment]
alternatively we can change the script to pin to the older version 

@Lukasa @weissi probably need to check nio as well

**Comment by ktoso** [comment]
Uff yeah, I may have hit this before 🤔 
Will check in other repos

**Review by weissi — APPROVED** [review]
Thank you! LGTM

**Comment by weissi** [comment]
> alternatively we can change the script to pin to the older version
> 
> @Lukasa @weissi probably need to check nio as well

@tomerd NIO seems okay, last release is 2.25.1 and the docs are for that very release.

**Comment by tomerd** [comment]
> > alternatively we can change the script to pin to the older version
> 
> > 
> 
> > @Lukasa @weissi probably need to check nio as well
> 
> 
> 
> @tomerd NIO seems okay, last release is 2.25.1 and the docs are for that very release.

looking at the code i think its susceptible to the same issue. it likely using a cached version which is why have not surfaced yet

**Pull request merged**
