### PR TITLE
Fix doc comment for redirectConfiguration

### PR DESCRIPTION
**Pull request by MaxDesiatov**
`redirectConfiguration` can't default to `false` as it's not a boolean value, and the default value is `RedirectConfiguration()`.

### CODE REVIEW

**Comment by MaxDesiatov** [comment]
Cant @swift-server-bot ever post just a single comment? 🤔

**Comment by Lukasa** [comment]
Swift server bot is just very enthusiastic.

**Comment by Lukasa** [comment]
@swift-server-bot test this please

**Comment by weissi** [comment]
CC @tomerd regarding the overly enthusiastic @swift-server-bot

**Comment by weissi** [comment]
@swift-server-bot add to whitelist

**Comment by artemredkin** [comment]
thank you, @MaxDesiatov !

**Pull request merged**
