### PR TITLE
add .git extensions to dependency URLs

### PR DESCRIPTION
**Pull request by daSkier**
This PR adds .git extensions to the Swift Package Manager dependencies that didn't include them. For me, this resolves issues that I have had with an error produced by Xcode when updating to the latest package versions if I'm editing the project which depends on AHC in an Xcode Workspace. 

image

The complete error is: `github.com: https://github.com/apple/swift-algorithms: The repository could not be found. Make sure a valid repository exists at the specified location and try again.`

Based on conversations in the Vapor Discord server, adding these extensions "shouldn't" make a difference to the dependency resolution done by swift package manager, however adding them resolves the error. 🤷

### CODE REVIEW

**Comment by PeterAdams-A** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
I am very surprised to learn this has an impact. Are you using package mirroring?

**Comment by daSkier** [comment]
> Are you using package mirroring?

No.

**Comment by Lukasa** [comment]
Hmm, do you have a Feedback Assistant report for this? I'm trying to work out why Xcode would behave this way, as I've never seen it before.

**Comment by daSkier** [comment]
I have not filed a feedback. I'm happy to if that helps. And, if you have any suggestion on what would be relevant to include please let me know. I can make sure to include it.

**Comment by daSkier** [comment]
I don't remember if this issue started for me before or after I started using Xcode 16. I could try it in Xcode 15 to see if it happens there too. (I don't know if the Xcode version would/could impact this)

**Comment by Lukasa** [comment]
Would it be possible to file a Feedback Assistant report? My recommendation would be to see if you can reproduce this in a small workspace that you can attach to the report, along with information about the Xcode version.

**Comment by daSkier** [comment]
I'm definitely having difficulty figuring out how to reproduce this in a small project at the moment, but I have also figured out how to solve my immediate issues. 

If I do the following I can get Xcode to fetch new package versions: 
- use Xcode's File > Packages > Reset Package Caches and stop the process once it finishes the "Resetting package cache" based on the status displayed in the top the progress bar (unsure of the technical name). 
- Delete the workspace's internal Package.resolved file within the package contents (e.g. WorkspaceTest.xcworkspace > xcshareddata > swiftpm > Package.resolved). 
- Have Xcode resolve the latest versions by using File > Packages > Update to Latest Package Versions
- Once again trigger the Reset Package Caches

I'll keep looking to see if I can reproduce the issue with a small sample project.

**Comment by Lukasa** [comment]
That's an interesting data point. If you do that series of steps you should end up with a new Package.resolved file: what does it look like?

**Comment by MahdiBM** [comment]
I was the one who suggested trying adding .git to those repo urls (and subsequently suggested a PR), and I'm not surprised that it worked, although it certainly shouldn't work.

I had heard about some repo/url handling behavior differences/problems when using .git or not using .git in SwiftPM before, so I gave it chance that adding .git might have an effect on this new bug.

I understand and appreciate if anyone wants to find the root of the problem, but generally speaking, as far as this PR goes, I think this is still mergable even assuming it doesn't actually fix any Xcode problems.
The PR unifies all the repo urls to have a .git extention, and having .git in a git repository is also somewhat of an standard by itself 🙂.
That's at least what my thought-process was when suggesting to make a PR.

**Comment by FranzBusch** [comment]
Can we open an issue on SwiftPM for this. We can certainly make sure that all of our repos are using `.git` but this needs to be fixed in Swift PM itself cc @dschaefer2

**Review by FranzBusch — APPROVED** [review]
Approving this to get it aligned with our other dependencies here

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
@swift-server-bot add to allowlist

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by Lukasa** [comment]
@swift-server-bot add to allowlist

**Pull request merged**
