### PR TITLE
replace preconditions with errors

### PR DESCRIPTION
**Pull request by artemredkin**
Will address #49 as well

Before this PR, `channel.close` was called after `Task` promise was fulfilled. This introduced a slight delay before receiving `.end` and closing the channel. This in turn could lead to a situation where we could receive `.head` right after `.end`, which is allowed by HTTP protocol (keep-alive) but is not currently supported (pending connection pool work) by `ResponseAccumulator`. In order to address this, we need to close channel immediately after receiving `.end`.

### CODE REVIEW

**Comment by artemredkin** [comment]
I'm trying to add a test, but it's not that straitforward :) NIO is pretty good at detecting when you do stupid things in your `HTTPServerHandler` :D

**Comment by artemredkin** [comment]
Test added

**Comment by artemredkin** [comment]
@weissi see #49, we receive `head`, `end`, `head` in some cases, but it's correct in terms of http protocol I think, but `HTTPResponseAccumulator` cannot handle second response on the same connection, I will investigate why channel was not closed

**Comment by artemredkin** [comment]
@weissi I think `channel.close` happens too late, we receive `.end` and succeed the `promise` but callback (see line 358 in `HTTPHandler.swift`) on it's future is not called before we receive another `channelRead`, this is how we get into this inconsistent state.

**Comment by weissi** [comment]
@artemredkin cool, but that should be fixed then, no?

**Comment by artemredkin** [comment]
Question is, why task futureResult callback is called so late? It seems we need to call context.close right away in all cases

**Comment by artemredkin** [comment]
@weissi I reverted back to preconditions (preconditions in redirect handler will be replaced by #67), real issue was that we were closing channel too late, I propose to close channel immediately instead of relying on futureResult callback.

**Comment by weissi** [comment]
@artemredkin mind fixing the PR description and adding a good explanation of when exactly this will help? Also we definitely need a test case that proves this is effective.

**Comment by artemredkin** [comment]
@weissi done

**Comment by artemredkin** [comment]
This is not needed at all, underlying problem is solved by NIO:
https://github.com/apple/swift-nio/pull/1093/files

**Comment by weissi** [comment]
@artemredkin released as swift-nio 2.6.1

**Pull request closed without merging**
